#!/usr/bin/env bash
# Using the while loop to repeat the output 10 times

# Initialize a counter variable
count=1

while (( count <= 10 )); do
  echo "Best School"
  if (( count == 9 )); then
    echo "Hi"
  fi
  # Increment the counter
  ((count++))
done
