#!/usr/bin/env bash
# Bash script that displays numbers from 1 to 20 and:

# Initialize a counter variable
count=1

while (( count <= 20 )); do

  echo "${count}"

  case $count in
    4) echo "bad luck from China";;
    9) echo "bad luck from Japan";;
    17) echo "bad luck from Italy";;
  esac

  # Increment the counter
  ((count++))
done
